DELETE http://localhost:3003/api/blogs/6686736e699698f1cd2c2277
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2luVGVzdCIsImlkIjoiNjY4NjUxMzhiYjkyMTg1Y2E3MzFjODU5IiwiaWF0IjoxNzIwMDg3MzkxfQ.nteAupAN3uycTvIOxUR3UlinMprejKxX29bRphJVQOw
